# Generated by Django 2.0.2 on 2018-02-27 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, default='ERR-SHOULD-NEVER-SEE-THIS-CALL-911', max_length=300, verbose_name='Name')),
                ('org_contact', models.CharField(blank=True, max_length=300, verbose_name='Contact')),
                ('org_email', models.EmailField(blank=True, default='', max_length=254)),
                ('load_vi_time', models.DateTimeField(auto_now_add=True)),
                ('last_vi_edit', models.DateTimeField(auto_now=True)),
                ('org_creator', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='org_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
