# Generated by Django 2.0.2 on 2018-02-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Name'),
        ),
    ]
