# Generated by Django 2.0.2 on 2018-02-28 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0003_auto_20180227_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assess_name', models.CharField(blank=True, default='', max_length=300, verbose_name='assess_name')),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('assess_creator', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='assess_creator', to=settings.AUTH_USER_MODEL)),
                ('assess_org', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='assess_creator', to='org.Org')),
            ],
        ),
    ]
