# Generated by Django 2.0.2 on 2018-03-02 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assess_creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='assess_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assess_name',
            field=models.CharField(default='Name', max_length=300, verbose_name='assess_name'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assess_org',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='assess_org', to='org.Org'),
        ),
        migrations.AlterField(
            model_name='org',
            name='org_contact',
            field=models.CharField(default='Contact', max_length=300, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='org',
            name='org_creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='org_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='org',
            name='org_email',
            field=models.EmailField(default='none@none.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(default='Name', max_length=300, verbose_name='Name'),
        ),
    ]
