# Generated by Django 2.0.2 on 2018-03-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20180302_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
