# Generated by Django 2.0.2 on 2018-03-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_auto_20180302_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_name',
            field=models.CharField(default='Name', max_length=300, verbose_name='Name'),
        ),
    ]
