# Generated by Django 2.0.2 on 2018-02-25 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RVTvInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvt_vi_batch', models.IntegerField(null=True)),
                ('rvt_vi_vm', models.CharField(blank=True, max_length=300, verbose_name='VM Name')),
                ('rvt_vi_powerstate', models.CharField(blank=True, help_text='TESTING', max_length=300, verbose_name='Power State')),
                ('rvt_vi_guest_state', models.CharField(blank=True, max_length=300, verbose_name='Guest OS State')),
                ('rvt_vi_provisioned_mb', models.IntegerField(null=True)),
                ('rvt_vi_in_use_mb', models.IntegerField(null=True)),
                ('rvt_vi_unshared_mb', models.IntegerField(null=True)),
                ('load_vi_time', models.DateTimeField(auto_now_add=True)),
                ('last_vi_edit', models.DateTimeField(auto_now=True)),
                ('rvt_vi_user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vi_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
