# Generated by Django 2.0.2 on 2018-02-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_batch',
            field=models.CharField(blank=True, default='ERR', max_length=300, verbose_name='Batch'),
        ),
    ]
