# Generated by Django 2.0.2 on 2018-02-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0002_auto_20180226_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_filename',
            field=models.CharField(blank=True, default='ERR', max_length=300, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_batch',
            field=models.IntegerField(null=True),
        ),
    ]
