# Generated by Django 2.0.2 on 2018-02-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20180227_1733'),
        ('rvt', '0003_auto_20180226_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_org',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vi_org', to='org.Org'),
        ),
    ]
