# Generated by Django 2.0.2 on 2018-02-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0004_rvtvinfo_rvt_vi_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_org',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='org', to='org.Org'),
        ),
    ]
