# Generated by Django 2.0.2 on 2018-02-27 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0005_auto_20180227_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_org',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='org', to='org.Org'),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vi_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
