# Generated by Django 2.0.2 on 2018-02-27 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0007_auto_20180227_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvtvinfo',
            name='org',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='org', to='org.Org'),
        ),
    ]
