# Generated by Django 2.0.2 on 2018-03-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_auto_20180302_0500'),
        ('rvt', '0010_auto_20180227_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvtvinfo',
            name='rvt_vi_org',
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_assessment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vi_assessment', to='org.Assessment'),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_filename',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_guest_state',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_powerstate',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_vm',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
