# Generated by Django 2.0.2 on 2018-03-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0011_auto_20180302_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvtvinfo',
            old_name='last_vi_edit',
            new_name='last_edit',
        ),
        migrations.RenameField(
            model_name='rvtvinfo',
            old_name='load_vi_time',
            new_name='load_time',
        ),
        migrations.RemoveField(
            model_name='rvtvinfo',
            name='rvt_vi_guest_state',
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_cluster',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_cpus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_datacenter',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_disks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_dnsname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_folder',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_host',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_hwversion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_memory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_nics',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_os_config',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_os_uuid',
            field=models.CharField(blank=True, default='UNSET', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_os_vmtools',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_path',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_rsrcpool',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_powerstate',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_vm',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
