# Generated by Django 2.0.2 on 2018-03-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rvt', '0013_auto_20180304_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVTvDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvt_vd_vmid', models.CharField(blank=True, max_length=300, null=True)),
                ('rvt_vd_disk', models.CharField(default='UNSET', max_length=300)),
                ('rvt_vd_capacitymb', models.IntegerField(null=True)),
                ('rvt_vd_diskmode', models.CharField(blank=True, max_length=300, null=True)),
                ('rvt_vd_thin', models.BooleanField(default=False)),
                ('rvt_vd_controller', models.CharField(default='UNSET', max_length=300)),
                ('rvt_vd_path', models.CharField(default='UNSET', max_length=300)),
                ('rvt_vd_annotation', models.CharField(default='UNSET', max_length=300)),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('rvt_vd_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vd_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='rvtvinfo',
            old_name='rvt_vi_os_uuid',
            new_name='rvt_vi_uuid',
        ),
        migrations.AddField(
            model_name='rvtvdisk',
            name='rvt_vd_vinfo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vd_vinfo', to='rvt.RVTvInfo'),
        ),
    ]
