# Generated by Django 2.0.2 on 2018-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0014_auto_20180304_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rvtvdisk',
            name='rvt_vd_vinfo',
        ),
        migrations.AddField(
            model_name='rvtvdisk',
            name='rvt_vi_batch',
            field=models.IntegerField(null=True),
        ),
    ]
