# Generated by Django 2.0.2 on 2018-03-04 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rvt', '0015_auto_20180304_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVTvPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvt_vi_batch', models.IntegerField(null=True)),
                ('rvt_vp_vmid', models.CharField(blank=True, max_length=300, null=True)),
                ('rvt_vp_disk', models.CharField(default='UNSET', max_length=300)),
                ('rvt_vp_capacitymb', models.IntegerField(null=True)),
                ('rvt_vp_consumedmb', models.IntegerField(null=True)),
                ('rvt_vp_freemb', models.IntegerField(null=True)),
                ('rvt_vp_annotation', models.CharField(default='UNSET', max_length=300)),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('rvt_vp_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
