# Generated by Django 2.0.2 on 2018-03-04 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rvt', '0017_rvtvdatastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='RVTvHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvt_vi_batch', models.IntegerField(null=True)),
                ('rvt_vh_hostname', models.CharField(blank=True, max_length=300, null=True)),
                ('rvt_vh_datacenter', models.CharField(blank=True, max_length=300, null=True)),
                ('rvt_vh_cluster', models.CharField(blank=True, max_length=300, null=True)),
                ('rvt_vh_cputype', models.CharField(blank=True, max_length=300, null=True)),
                ('rvt_vh_speed', models.IntegerField(null=True)),
                ('rvt_vh_socketcount', models.IntegerField(null=True)),
                ('rvt_vh_socketcores', models.IntegerField(null=True)),
                ('rvt_vh_cores', models.IntegerField(null=True)),
                ('rvt_vh_cpu_usagepercent', models.IntegerField(null=True)),
                ('rvt_vh_memorymb', models.IntegerField(null=True)),
                ('rvt_vh_mem_usagepercent', models.IntegerField(null=True)),
                ('rvt_vh_vmcount', models.IntegerField(null=True)),
                ('rvt_vh_vmpercore', models.IntegerField(null=True)),
                ('rvt_vh_vcpucount', models.IntegerField(null=True)),
                ('rvt_vh_vcpupercore', models.IntegerField(null=True)),
                ('rvt_vh_vram', models.IntegerField(null=True)),
                ('rvt_vh_usedmem', models.IntegerField(null=True)),
                ('rvt_vh_swapmem', models.IntegerField(null=True)),
                ('rvt_vh_balloonmem', models.IntegerField(null=True)),
                ('rvt_vh_evc', models.IntegerField(null=True)),
                ('rvt_vh_maxevc', models.IntegerField(null=True)),
                ('rvt_vh_esxversion', models.IntegerField(null=True)),
                ('rvt_vh_boottime', models.CharField(blank=True, max_length=300, null=True)),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('rvt_vh_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='rvt_vh_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
