# Generated by Django 2.0.2 on 2018-03-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0018_rvtvhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvtvhost',
            name='rvt_vh_esxversion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='rvtvhost',
            name='rvt_vh_evc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rvtvhost',
            name='rvt_vh_maxevc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
