# Generated by Django 2.0.2 on 2018-03-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0020_rvtvinfo_rvt_vi_sdkserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_sdks_type',
            field=models.CharField(blank=True, default='UNSET', max_length=300, null=True),
        ),
    ]
