# Generated by Django 2.0.2 on 2018-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0021_rvtvinfo_rvt_vi_sdks_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvtvinfo',
            name='rvt_vi_filename_orig',
            field=models.CharField(default='UNSET', max_length=300),
        ),
        migrations.AlterField(
            model_name='rvtvinfo',
            name='rvt_vi_filename',
            field=models.CharField(default='UNSET', max_length=300),
        ),
    ]
