# Generated by Django 2.0.2 on 2018-03-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvt', '0022_auto_20180305_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rvtvdatastore',
            old_name='rvt_vs_provisioinedmb',
            new_name='rvt_vs_provisionedmb',
        ),
    ]
